// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for the dev Firebase project (fridgefinder-app-dev).
///
/// Generated via:
/// ```bash
/// flutterfire configure --project=fridgefinder-app-dev --out=lib/firebase_options_dev.dart --platforms=android,ios
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxyghMo-Ar_RzxK41l7cM6VjtkJjBn5dg',
    appId: '1:284914819627:android:9ba615d2307067a90a006e',
    messagingSenderId: '284914819627',
    projectId: 'fridgefinder-app-dev',
    databaseURL: 'https://fridgefinder-app-dev-default-rtdb.firebaseio.com',
    storageBucket: 'fridgefinder-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo7O3AwEsIsIJNojmRv45RcQO9Ef-FvtE',
    appId: '1:284914819627:ios:337f63ebf86b11e00a006e',
    messagingSenderId: '284914819627',
    projectId: 'fridgefinder-app-dev',
    databaseURL: 'https://fridgefinder-app-dev-default-rtdb.firebaseio.com',
    storageBucket: 'fridgefinder-app-dev.firebasestorage.app',
    iosClientId: '284914819627-liq1j0mvtnql3j423gat9bs1nd6g39t2.apps.googleusercontent.com',
    iosBundleId: 'com.fridgefinder.fridgefinderFlutterApp',
  );

}